// Generated by CodeAssist from the project model. Review before you rely on it.

plugins {
    id("com.android.application") version "8.13.0" apply false
    id("org.jetbrains.kotlin.android") version "2.4.0" apply false
}
